version: '3'
services:
  postgres:
    image: postgres:12.2-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: user_storage
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
  rabbitmq:
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672
  user-storage:
    image: user-storage
    restart: always
    ports:
      - 8080:8080
    links:
      - rabbitmq:rabbitmq
      - postgres:postgres
